### ISSUE TITLE
linux_syslog: should extract full sudo commands

### ISSUE THREAD

**Issue by corey-thuen-gravwell** [gravwell/kits#100]
Queries in the linux_syslog kit utilize the `kv` module to split the syslog Message field. They use the "-d" flag and provide " ; " as the option. This means a space OR a semicolon will act as a delimiter. This should be "-dall" for the delimiter.

Old query example:

```
tag=$SYSLOG syslog Appname==sudo Message Hostname
| regex -e Message "(?P<sudoing_user>\S+) : (?P<args>.+)"
| kv -e args -ld -sep "=" -d " ; " TTY PWD COMMAND
| table TIMESTAMP Hostname sudoing_user TTY PWD COMMAND
```

Fixed example:

```
tag=$SYSLOG syslog Appname==sudo Message Hostname
| regex -e Message "(?P<sudoing_user>\S+) : (?P<args>.+)"
| kv -e args -ld -sep "=" -dall " ; " TTY PWD COMMAND
| table TIMESTAMP Hostname sudoing_user TTY PWD COMMAND
```

This change properly extracts "/usr/bin/apt upgrade" from `TTY=pts/5 ; PWD=/home/foobar ; USER=root ; COMMAND=/usr/bin/apt upgrade`

**Comment by kris-watts-gravwell** [comment]
https://github.com/gravwell/kits/pull/106
