### ISSUE TITLE
Corelight UID actionable is too strict on length  - 

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/kits#109]
## What are the steps to reproduce this issue?

1. regex is `(\s|^)(?<uid>(C|F)([a-zA-Z0-9]{13,17}))(\s|$)`
2. but i have UIDs that are `CHnVyi4ypEs0Wrqe13`
3. Also it doesn't work with JSON data because of the surrounding quotes

should probably be: `(\s|^|")(?<uid>(C|F)([a-zA-Z0-9]{13,19}))(\s|$|")`

**Comment by john-floren-gravwell** [comment]
kris says it looks good
