### ISSUE TITLE
Gravwell Kit: Self Logging has some wonkiness

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/kits#142]
## User Overview
Active Users tile is pretty bad, that really should just be a more elaborate "Total Queries by User" with more stats
Failed logins needs to be on the user overview dashboard too
Better visualization of "query share" per user (donut or pie chart)

## Automations Dashboard
Shows UID and ID, that sucks, show username, and flow/script/search name

Most active users shows uid, that sucks, enumerate username

"New Automations" is really Automation Updates

"Failed Automations" shouldnt' have avg runtime, just error and name

## Needed new stuff
The abusive queries list should be on the query overview dashboard

**Comment by kris-watts-gravwell** [comment]
average runtime is kind of useful, keeping it

**Comment by john-floren-gravwell** [comment]
hand-built and installed, looks good
