### ISSUE TITLE
Add banner image to all kits

### ISSUE THREAD

**Issue by traetox** [gravwell/kits#28]
Every kit should use a symlink on the metadata to point at file/*.contents.

We also need to establish a banner for every kit metadata, see what was done in the linux_syslog kit in this PR: https://github.com/gravwell/kits/pull/27 and https://github.com/gravwell/kits/pull/29

**Comment by john-floren-gravwell** [comment]
https://github.com/gravwell/internal-kits/pull/99 did some of it.

I'd like to punt the rest of this for later because it's *all* kinda haphazard and we still need to figure out if it even makes sense to have kit.metadata as this separate file instead of just using the fields defined in MANIFEST

**Comment by john-floren-gravwell** [comment]
Every kit currently on the kitserver appears to have an acceptable banner image. We have decided to address metadata vs. manifest stuff at a later time.
