### ISSUE TITLE
update gravwell kit for 5.0 release

### ISSUE THREAD

**Issue by djfritz** [gravwell/kits#63]

**Comment by traetox** [comment]
Gravwell kit is extracting tags weird on the `Gravwell Query Overview` dashboard in 5.0.1.
![Screenshot from 2022-04-27 19-12-22](https://user-images.githubusercontent.com/1326392/165658059-2ef8ac26-5619-46cf-81cd-ca9c45a0bcb0.png)
![Screenshot from 2022-04-27 19-12-06](https://user-images.githubusercontent.com/1326392/165658064-b7ba6765-de2b-4891-af0d-0e685ab1967d.png)

**Comment by kris-watts-gravwell** [comment]
done
